### ISSUE TITLE
Error building frontend with the tutorial steps

### ISSUE THREAD

**Issue by erikriver** [aragon/aragon-cli#215]
Hello, following the steps in the tutorial, I've this error:

```
$ aragon init aragontutorial.aragonpm.eth react
$ cd aragontutorial
$ aragon run

[14:05:03] Start a local Ethereum network [started]
[14:05:03] Starting a local chain from snapshot [started]
[14:05:03] Local chain started at port 8545 [title changed]
[14:05:03] Local chain started at port 8545 [completed]
[14:05:03] Start a local Ethereum network [completed]
[14:05:03] Check IPFS [started]
[14:05:03] Start IPFS [started]
[14:05:04] → Starting IPFS at port: 5001
[14:05:05] Start IPFS [completed]
[14:05:05] Add local files [started]
[14:05:06] Add local files [completed]
[14:05:06] Check IPFS [completed]
[14:05:06] Publish app to APM [started]
[14:05:06] Deploy contract [started]
[14:05:06] Compile contracts [started]
[14:05:08] Compile contracts [completed]
[14:05:08] Deploy 'CounterApp' to network [started]
[14:05:08] → Deploying 'CounterApp' to network
[14:05:08] Deploy 'CounterApp' to network [completed]
[14:05:08] Deploy contract [completed]
[14:05:08] Automatically bump version [started]
[14:05:09] Automatically bump version [skipped]
[14:05:09] → Starting from initial version
[14:05:09] Determine contract address for version [started]
[14:05:09] Determine contract address for version [completed]
[14:05:09] Building frontend [started]
[14:05:09] → npm run build: 
> app-name@1.0.0 build /Users/erik/Develop/aragontutorial
> npm run sync-assets && npm run build:app && npm run build:script


[14:05:09] → npm run build: 
> app-name@1.0.0 sync-assets /Users/erik/Develop/aragontutorial
> copy-aragon-ui-assets -n aragon-ui ./dist


[14:05:09] → npm run build: 
Aragon UI assets copied to dist/aragon-ui

[14:05:09] → npm run build: 
> app-name@1.0.0 build:app /Users/erik/Develop/aragontutorial
> parcel build app/index.html -d dist/ --public-url '.' --no-cache


[14:05:11] → npm run build: 🚨  /Users/erik/Develop/aragontutorial/app/main.js:50:11: Unexpected token (50:11

[14:05:11] → npm run build:   48 |   }
  49 |   render() {
> 50 |     return <App {...this.state} />
     |           ^
  51 |   }
  52 | }
  53 | ReactDOM.render(

[14:05:11] Building frontend [failed]
[14:05:11] → Command failed: npm run build
```

I'm using macOS High Sierra and my versions are:
``` 
$ node -v
v8.9.4

$ npm -v
6.4.1

$ aragon -v
5.0.0
```

Could you help me to understand the cause of this error?
Regards.

**Comment by 0x6431346e** [comment]
Hello Erik,
The building of the frontend is failing because of the new version of `parcel-bundler` (`v1.10`).
While we are working on this issue you can try to pin parcel to `v1.9.7` by running:
- `npm un parcel-bundler`
- `npm i -D parcel-bundler@1.9.7`

**Comment by 0x6431346e** [comment]
You might also run into this error:
> 🚨 Build Error
/home/daniel/.aragon/wrapper-fcebf55d1af6c574a92587e2a1d3ac8c00804d16/src/index.html: Conflicting babel versions found in .babelrc. Make sure all of your plugins and presets depend on the same major version of babel.

This is `aragon-core` (the wrapper) failing to build because of parcel's "minor" update :disappointed: :

Until we publish `v5.0.1` you can try:
1. `cd /home/<username>/.aragon/wrapper-fcebf55d1af6c574a92587e2a1d3ac8c00804d16`
Note: on Windows it's `/Users/<username>/.aragon/...`
2. `npm install --save-dev parcel-bundler@1.9.7`

**Comment by erikriver** [comment]
It works! Thanks @0x6431346e 

Regards.

**Comment by 0x6431346e** [comment]
Should be fixed in the next release

**Comment by rperez89** [comment]
hi @0x6431346e i followed your steps but i am still getting that error, i am with node 8.10 any idea?

**Comment by rperez89** [comment]
Thanks!! now it's working!
